version: "3"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - file-upload-frontend

  file-upload-frontend:
    restart: always
    build: .
    image: file-upload-frontend:latest
    container_name: file-upload-frontend
    hostname: file-upload-frontend
    command: serve -s build -l 80
    volumes:
      - .:/app
    expose:
      - 80
