artifacts:
  files:
  - transformed.yaml
  type: zip
phases:
  build:
    commands:
    - cd backend/.chalice/packaged
    - chalice package --merge-template resource_policies.yaml --template-format yaml . --stage dev
    - aws cloudformation package --template-file sam.yaml --s3-bucket ${APP_S3_BUCKET} --output-template-file transformed.yaml
  install:
    commands:
    - pip install 'chalice>=1.22.0,<1.23.0'
    - pip install -r backend/requirements.txt
    runtime-versions:
      python: '3.8'
version: '0.2'
